version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

server:
  command: 'php ./vendor/bin/roadrunner-worker'
  relay: 'unix:///var/run/rr/rr.sock'
  env:
    - APP_BASE_PATH: /app

logs:
  mode: raw
  level: info
  encoding: console
  output: stdout

http:
  address: 0.0.0.0:8080
  max_request_size: 200
  middleware: ['headers', 'static', 'gzip']
  uploads:
    forbid: ['.php', '.exe', '.bat', '.sh']
  static:
    dir: 'public'
    forbid: ['.php']
  pool:
    num_workers: 8
    max_jobs: 128
    supervisor:
      max_worker_memory: 128
      exec_ttl: 60s

metrics:
  address: 0.0.0.0:2112

status:
  address: 0.0.0.0:8888
