version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

server:
  command: 'php ./vendor/bin/roadrunner-worker'
  relay: 'unix:///var/run/rr/rr.sock'
  env:
    - APP_BASE_PATH: /app

logs:
  mode: raw
  level: info
  encoding: console
  output: stdout
  channels:
    http:
      mode: production
      encoding: json
      output: stderr

http:
  address: 0.0.0.0:8080
  http2:
    h2c: true
  max_request_size: 200
  middleware: [ "headers", "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat", ".sh" ]
  headers:
    response:
      "X-Powered-By": "RoadRunner"
  static:
    dir: "public"
    forbid: [ ".php" ]
  pool:
    num_workers: 16
    max_jobs: 256
    supervisor:
      max_worker_memory: 128
      exec_ttl: 60s # diff

metrics:
  address: 0.0.0.0:2112

status:
  address: 127.0.0.1:8082
